[tool.mypy]
python_version = "3.8"
warn_return_any = false
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false
disallow_untyped_decorators = false
no_implicit_optional = false
warn_redundant_casts = false
warn_unused_ignores = false
warn_no_return = false
warn_unreachable = false
strict_equality = false

# Ignore specific error types globally
disable_error_code = [
    "attr-defined",  # Cannot access attribute "X" for class "Y"
    "assignment",    # Argument of type "X" cannot be assigned to parameter "Y"
    "index",         # Index of type "X" cannot be used to index "Y"
    "operator",      # Unsupported operand types for "X"
    "misc",          # Miscellaneous errors
]

[tool.pyright]
typeCheckingMode = "basic"
reportUnknownMemberType = "none"
reportUnknownVariableType = "none"
reportUnknownArgumentType = "none"
reportUnknownLambdaType = "none"
reportUnknownParameterType = "none"
reportMissingTypeStubs = "none"
reportUntypedFunctionDecorator = "none"
reportUntypedClassDecorator = "none"
reportUntypedBaseClass = "none"
reportUntypedNamedTuple = "none"
reportPrivateUsage = "none"
reportConstantRedefinition = "none"
reportIncompatibleMethodOverride = "none"
reportIncompatibleVariableOverride = "none"
reportInconsistentConstructor = "none"
reportOverlappingOverloads = "none"
reportMissingSuperCall = "none"
reportDuplicateImport = "none"
reportWildcardImportFromLibrary = "none"
reportOptionalSubscript = "none"
reportOptionalMemberAccess = "none"
reportOptionalCall = "none"
reportOptionalIterable = "none"
reportOptionalContextManager = "none"
reportOptionalOperand = "none"
reportUntypedImport = "none"
reportUntypedImport = "none" 